export const nivel = [
  {
    id: 1,
    descripcion: "En este primer nivel aprenderemos las Vocales",
    link: "/leccion/0",
    position: "izquierda",
    positionInfo: "rigth",
    cap: 1,
  },
  {
    id: 2,
    descripcion: "Aprende sobre numeros",
    link: "/leccion/4",
    position: "derecha",
    positionInfo: "left",
    cap: 1,
  },
  {
    id: 3,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "izquierda",
    positionInfo: "rigth",
    cap: 1,
  },
  {
    id: 4,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "izquierda",
    positionInfo: "rigth",
    cap: 2,
  },
  {
    id: 5,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "derecha",
    positionInfo: "left",
    cap: 2,
  },
  {
    id: 6,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "izquierda",
    positionInfo: "rigth",
    cap: 2,
  },
  {
    id: 7,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "izquierda",
    positionInfo: "rigth",
    cap: 3,
  },
];
