/*
export const nivel = [
  {
    id: 1,
    descripcion: "En este primer nivel aprenderemos las Vocales",
    link: "/leccion/0",
    position: "izquierda",
    positionInfo: "rigth",
    cap: 1,
  },
  {
    id: 2,
    descripcion: "Aprende sobre numeros",
    link: "/leccion/4",
    position: "derecha",
    positionInfo: "left",
    cap: 1,
  },
  {
    id: 3,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "izquierda",
    positionInfo: "rigth",
    cap: 1,
  },
  {
    id: 4,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "izquierda",
    positionInfo: "rigth",
    cap: 2,
  },
  {
    id: 5,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "derecha",
    positionInfo: "left",
    cap: 2,
  },
  {
    id: 6,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "izquierda",
    positionInfo: "rigth",
    cap: 2,
  },
  {
    id: 7,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "izquierda",
    positionInfo: "rigth",
    cap: 3,
  },
];
*/

export const seccionLevels = [
  {
    href: "numeros",
    titulo: "Números",
    levels: [
      {
        id: 1,
        descripcion: "Aprende sobre números",
        link: "/leccion/4",
        position: "izquierda",
        positionInfo: "rigth",
      },
      {
        id: 2,
        descripcion: "PROXIMAMENTE...",
        link: "",
        position: "derecha",
        positionInfo: "left",
      },
      {
        id: 3,
        descripcion: "PROXIMAMENTE...",
        link: "",
        position: "izquierda",
        positionInfo: "rigth",
      },
    ],
  },
  {
    href: "colores",
    titulo: "Colores",
    levels: [
      {
        id: 4,
        descripcion: "PROXIMAMENTE...",
        link: "/leccion/8",
        position: "izquierda",
        positionInfo: "rigth",
      },
      {
        id: 5,
        descripcion: "PROXIMAMENTE...",
        link: "",
        position: "derecha",
        positionInfo: "left",
      },
      {
        id: 6,
        descripcion: "PROXIMAMENTE...",
        link: "",
        position: "izquierda",
        positionInfo: "rigth",
      },
    ],
  },
  {
    href: "familia",
    titulo: "Familia",
    levels: [
      {
        id: 7,
        descripcion: "PROXIMAMENTE...",
        link: "/leccion/4",
        position: "izquierda",
        positionInfo: "rigth",
      },
      {
        id: 8,
        descripcion: "PROXIMAMENTE...",
        link: "",
        position: "derecha",
        positionInfo: "left",
      },
      {
        id: 9,
        descripcion: "PROXIMAMENTE...",
        link: "",
        position: "izquierda",
        positionInfo: "rigth",
      },
    ],
  },
  {
    href: "dias",
    titulo: "Días",
    levels: [
      {
        id: 10,
        descripcion: "PROXIMAMENTE...",
        link: "/leccion/4",
        position: "izquierda",
        positionInfo: "rigth",
      },
      {
        id: 11,
        descripcion: "PROXIMAMENTE...",
        link: "",
        position: "derecha",
        positionInfo: "left",
      },
      {
        id: 12,
        descripcion: "PROXIMAMENTE...",
        link: "",
        position: "izquierda",
        positionInfo: "rigth",
      },
    ],
  },
  {
    href: "meses",
    titulo: "Meses",
    levels: [
      {
        id: 13,
        descripcion: "PROXIMAMENTE...",
        link: "/leccion/4",
        position: "izquierda",
        positionInfo: "rigth",
      },
      {
        id: 14,
        descripcion: "PROXIMAMENTE...",
        link: "",
        position: "derecha",
        positionInfo: "left",
      },
      {
        id: 15,
        descripcion: "PROXIMAMENTE...",
        link: "",
        position: "izquierda",
        positionInfo: "rigth",
      },
    ],
  },
  {
    href: "preguntasBasicas",
    titulo: "Preguntas Basicas",
    levels: [
      {
        id: 16,
        descripcion: "PROXIMAMENTE...",
        link: "/leccion/4",
        position: "izquierda",
        positionInfo: "rigth",
      },
      {
        id: 17,
        descripcion: "PROXIMAMENTE...",
        link: "",
        position: "derecha",
        positionInfo: "left",
      },
      {
        id: 18,
        descripcion: "PROXIMAMENTE...",
        link: "",
        position: "izquierda",
        positionInfo: "rigth",
      },
    ],
  },
];
