export const nivel = [
  {
    nivel1: 1,
    descripcion: "En este primer nivel aprenderemos las Vocales",
    link: "/leccion/0",
    position: "center",
    positionInfo: "rigth",
    cap: 1,
  },
  {
    nivel2: 2,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "end",
    positionInfo: "left",
    cap: 1,
  },
  {
    nivel1: 3,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "center",
    positionInfo: "rigth",
    cap: 1,
  },
  {
    nivel2: 4,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "center",
    cap: 2,
  },
  {
    nivel1: 5,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "end",
    cap: 2,
  },
  {
    nivel2: 6,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "center",
    cap: 2,
  },
  {
    nivel1: 7,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "center",
    cap: 3,
  },
];
