export const nivel = [
  {
    id: 1,
    descripcion: "En este primer nivel aprenderemos las Vocales",
    link: "/leccion/0",
    position: "center",
    positionInfo: "rigth",
    cap: 1,
  },
  {
    id: 2,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "end",
    positionInfo: "left",
    cap: 1,
  },
  {
    id: 3,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "center",
    positionInfo: "rigth",
    cap: 1,
  },
  {
    id: 4,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "center",
    positionInfo: "rigth",
    cap: 2,
  },
  {
    id: 5,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "end",
    positionInfo: "left",
    cap: 2,
  },
  {
    id: 6,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "center",
    positionInfo: "rigth",
    cap: 2,
  },
  {
    id: 7,
    descripcion: "PROXIMAMENTE...",
    link: "",
    position: "center",
    positionInfo: "rigth",
    cap: 3,
  },
];
